before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: slug-rename
    ldflags:
      - -s -w -X github.com/emgag/slug-rename/internal/lib/version.Version={{.Version}} -X github.com/emgag/slug-rename/internal/lib/version.Commit={{.Commit}} -X github.com/emgag/slug-rename/internal/lib/version.Date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - files:
    - LICENSE
#    - README.md
checksum:
  name_template: 'checksums.txt'
